version: '3'
services:
  postgres:
    image: 'postgres:9.6'
    container_name: postgres-dsdeliver
    environment:
      - POSTGRES_DB=dsdeliver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
      - TZ=GMT
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
      
  rabbitmq: 
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    volumes:
      - '../dados-rabbitmq:/var/lib/rabbitmq/'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      
  mysql-nodezin:
    container_name: mysql-nodezin
    image: mysql
    volumes:
      - '../dados-mysql-nodezin:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodezin
      MYSQL_USER: nodezin
      MYSQL_PASSWORD: nodezin
